### ISSUE TITLE
simple-example OSC not working (Windows 11)

### ISSUE THREAD

**Issue by Esquilofrenik0** [ndr-brt/atom-p5js#8]
simple-example onOscMessage not working for me :( 

![image](https://user-images.githubusercontent.com/75098525/176120170-5380f784-850d-4475-9377-c8bf2ed54fdc.png)
![image](https://user-images.githubusercontent.com/75098525/176120195-15ee0966-0459-42e3-9ed9-d5103894b94a.png)

**Comment by ndr-brt** [comment]
Hi, sorry for the delay, the problem is that you need to enable the `osc server` check in the plugin configuration.
I could improve the error message but since atom is going to be archived there's no good reason to do that.

Will leave this issue open for documentation

**Comment by ndr-brt** [comment]
At the end, thanks to Pulsar, I worked on this!

this happens because the OSC server was not active. with the new version 0.2.3 (under new name, see [p5js](https://web.pulsar-edit.dev/packages/p5js), please install it and uninstall `atom-p5js`) there is a check, if the server is not active and you try to execute a sketch that listens to OSC, you'll get an error and the sketch will start anyway
